kind: pipeline
type: docker
name: default

steps:
  - name: setup-qemu
    image: multiarch/qemu-user-static:register
    commands:
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

  - name: build-and-push
    image: docker:20.10.7
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    environment:
      DOCKER_BUILDKIT: 1
    commands:
      - docker buildx create --use
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/arm64,linux/amd64 -t rohitmisra44/homelab-pipeline-image:1.2.0 --push .
      - docker buildx imagetools inspect rohitmisra44/homelab-pipeline-image:1.2.0

trigger:
  event:
    - push
  branch:
    - main

services:
  - name: docker
    image: docker:20.10.7-dind
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - dockerd-entrypoint.sh
      - --host=tcp://0.0.0.0:2375
      - --host=unix:///var/run/docker.sock
    privileged: true
