---
kind: pipeline
name: default

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: rohitmisra44/homelab-pipeline-image:v1.2.0
      template: rohitmisra44/homelab-pipeline-image:v1.2.0-OS-ARCH
      platforms:
        - linux/amd64
        - linux/arm
        - linux/arm64
trigger:
  event:
    include:
      - push
      - pull_request