---
kind: pipeline
name: default

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: rohitmisra44/homelab-pipeline-image:v1.2.0
      template: rohitmisra44/homelab-pipeline-image:v1.2.0-OS-ARCH
      platforms:
        - linux/amd64
        - linux/arm
        - linux/arm64
trigger:
  event:
    include:
      - push
      - pull_request


kind: pipeline
type: docker
name: default

steps:
  - name: setup-buildx
    image: docker:20.10.7
    commands:
      - apk add --no-cache curl
      - |
        # Install buildx
        mkdir -p ~/.docker/cli-plugins/
        curl -sSL https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
        chmod +x ~/.docker/cli-plugins/docker-buildx
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --name multiarch --use
        docker buildx inspect --bootstrap

  - name: build-and-push
    image: docker:20.10.7
     volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    commands:
      - |
        # Define your Docker image name and tag
        IMAGE_NAME="rohitmisra44/homelab-pipeline-image:v1.2.0"
        IMAGE_TAG="latest"

        # Build and push multi-arch Docker images
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag $IMAGE_NAME:$IMAGE_TAG \
          --push .

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

services:
  - name: docker
    image: docker:20.10.7-dind
    privileged: true

trigger:
  branch:
    - main
