kind: pipeline
type: docker
name: default

steps:
  - name: build_amd64
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: rohitmisra44/homelab-pipeline-image
      tags: 1.2.0
      platforms: linux/amd64
      build_args:
        - TARGETPLATFORM=linux/amd64
      auto_tag: true
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
  
  - name: build_arm64
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: rohitmisra44/homelab-pipeline-image
      tags: 1.2.0
      platforms: linux/arm64
      build_args:
        - TARGETPLATFORM=linux/arm64
      auto_tag: true
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
  - name: manifest
    image: plugins/manifest
    settings:
      spec: manifest.tmpl
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

trigger:
  event:
    - push
  branch:
    - main

services:
  - name: docker
    image: plugins/docker:dind
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - dockerd-entrypoint.sh
      - --host=tcp://0.0.0.0:2375
      - --host=unix:///var/run/docker.sock
