kind: pipeline
type: docker
name: default

steps:
  - name: setup-buildx
    image: plugins/docker
    commands:
      - docker buildx create --name multiarch-builder --use
      - docker buildx inspect --bootstrap

  - name: build-and-push
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker buildx build --builder mybuilder --platform linux/arm64,linux/amd64 -t rohitmisra44/homelab-pipeline-image:1.2.0 --push .
      - docker buildx imagetools inspect rohitmisra44/homelab-pipeline-image:1.2.0

trigger:
  event:
    - push
  branch:
    - main

services:
  - name: docker
    image: plugins/docker:dind
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - dockerd-entrypoint.sh
      - --host=tcp://0.0.0.0:2375
      - --host=unix:///var/run/docker.sock
