kind: pipeline
type: docker
name: default

steps:
  - name: setup-qemu
    image: multiarch/qemu-user-static:register
    privileged: true
    commands:
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

  - name: build-arm64
    image: docker:20.10.7
    environment:
      DOCKER_BUILDKIT: 1
    commands:
      - docker buildx create --use
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/arm64 -t rohitmisra44/homelab-pipeline-image:arm64 --push .

  - name: build-amd64
    image: docker:20.10.7
    environment:
      DOCKER_BUILDKIT: 1
    commands:
      - docker buildx create --use
      - docker buildx inspect --bootstrap
      - docker buildx build --platform linux/amd64 -t rohitmisra44/homelab-pipeline-image:amd64 --push .

  - name: create-and-push-manifest
    image: docker:20.10.7
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    commands:
      - docker manifest create rohitmisra44/homelab-pipeline-image:1.2.0 rohitmisra44/homelab-pipeline-image:arm64 rohitmisra44/homelab-pipeline-image:amd64
      - docker manifest push rohitmisra44/homelab-pipeline-image:1.2.0

  - name: build-and-push
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: rohitmisra44/homelab-pipeline-image
      tags: latest

trigger:
  event:
    - push
  branch:
    - main

services:
  - name: docker
    image: docker:dind
    privileged: true
